/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vote_pebble_zkp_AnonCred1 */

#ifndef _Included_vote_pebble_zkp_AnonCred1
#define _Included_vote_pebble_zkp_AnonCred1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vote_pebble_zkp_AnonCred1
 * Method:    jniGenerateCredential
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_vote_pebble_zkp_AnonCred1_jniGenerateCredential
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     vote_pebble_zkp_AnonCred1
 * Method:    jniHashMerkleTree
 * Signature: ([B[BI)I
 */
JNIEXPORT jint JNICALL Java_vote_pebble_zkp_AnonCred1_jniHashMerkleTree
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     vote_pebble_zkp_AnonCred1
 * Method:    jniProve
 * Signature: ([B[B[B[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_vote_pebble_zkp_AnonCred1_jniProve
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     vote_pebble_zkp_AnonCred1
 * Method:    jniVerify
 * Signature: ([B[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_vote_pebble_zkp_AnonCred1_jniVerify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
